# Generated by Django 2.1.2 on 2019-01-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCheckboxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=15)),
                ('form_data_checkbox', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedFormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=15)),
                ('form_data', models.TextField()),
                ('form_data_mod', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedSelectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=15)),
                ('form_data_select', models.TextField()),
                ('saved_form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formprocessor.SavedFormData')),
            ],
        ),
        migrations.AddField(
            model_name='savedcheckboxdata',
            name='saved_form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formprocessor.SavedFormData'),
        ),
    ]
