# Generated by Django 2.1.2 on 2019-01-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
