# Generated by Django 2.1.2 on 2019-01-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0002_auto_20190105_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
