# Generated by Django 2.1.2 on 2019-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0004_savedformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedformdata',
            name='form_name',
            field=models.CharField(default='no name', max_length=15),
            preserve_default=False,
        ),
    ]
