# Generated by Django 2.1.2 on 2019-01-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0005_savedformdata_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCheckboxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data_checkbox', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedSelectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data_select', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='savedformdata',
            name='form_data_other_fields',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedselectdata',
            name='saved_form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formprocessor.SavedFormData'),
        ),
        migrations.AddField(
            model_name='savedcheckboxdata',
            name='saved_form_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formprocessor.SavedFormData'),
        ),
    ]
