# Generated by Django 2.1.2 on 2019-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0006_auto_20190111_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcheckboxdata',
            name='form_name',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedselectdata',
            name='form_name',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
