# Generated by Django 2.1.2 on 2019-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0007_auto_20190111_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedformdata',
            name='form_data_other_fields',
        ),
        migrations.AddField(
            model_name='savedformdata',
            name='form_data_mod',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
