# Generated by Django 2.1.2 on 2019-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formprocessor', '0008_auto_20190111_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOptionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=15)),
                ('options_data', models.TextField()),
            ],
        ),
    ]
